#!/usr/bin/env bash
# ===========================================================================
# File Manager SaaS — one-click bootstrap for a blank Ubuntu VPS
#
# Run as root (or with sudo) on a fresh Ubuntu 22.04 / 24.04:
#
#   curl -fsSL https://raw.githubusercontent.com/BetaZen-InfoTech/file-manager/main/scripts/bootstrap.sh \
#     | sudo bash -s -- --domain files.yourdomain.com --email you@yourdomain.com
#
# What it does (≈ 5–10 minutes):
#   - apt update + base packages (curl, git, nginx, ufw, fail2ban)
#   - Node.js 20.x + npm + pm2
#   - Docker + docker compose plugin
#   - Certbot
#   - Clones the repo into /var/www/app  (or pulls if it exists)
#   - Auto-generates /var/www/app/.env with random secrets
#   - Starts MongoDB + MinIO via docker compose (localhost-only ports)
#   - npm ci + npm test + npm run build
#   - Seeds the first super_admin (idempotent)
#   - Writes Nginx vhost + obtains LE SSL cert (if DNS resolves)
#   - Installs cron jobs (expire-links / purge-trash / recount / orphan / backup)
#   - Starts under PM2 + enables boot-time autostart
#
# Flags:
#   --domain  <fqdn>     domain that points to this VPS (required for SSL)
#   --email   <addr>     email for Let's Encrypt (required for SSL)
#   --repo    <url>      repo URL (default: https://github.com/BetaZen-InfoTech/file-manager.git)
#   --branch  <name>     branch (default: main)
#   --dir     <path>     install dir (default: /var/www/app)
#   --skip-ssl           don't run certbot (use if DNS not ready yet — re-run later)
#   --admin-email <e>    super_admin email (otherwise will prompt at end)
#   --admin-pass  <p>    super_admin password
# ===========================================================================
set -euo pipefail

DOMAIN=""
EMAIL=""
REPO="https://github.com/BetaZen-InfoTech/file-manager.git"
BRANCH="main"
APP_DIR="/var/www/app"
SKIP_SSL=0
ADMIN_EMAIL=""
ADMIN_PASS=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain) DOMAIN="$2"; shift 2;;
    --email) EMAIL="$2"; shift 2;;
    --repo) REPO="$2"; shift 2;;
    --branch) BRANCH="$2"; shift 2;;
    --dir) APP_DIR="$2"; shift 2;;
    --skip-ssl) SKIP_SSL=1; shift;;
    --admin-email) ADMIN_EMAIL="$2"; shift 2;;
    --admin-pass) ADMIN_PASS="$2"; shift 2;;
    *) echo "unknown flag: $1"; exit 2;;
  esac
done

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root (or with sudo)."
  exit 1
fi

c_blue()  { printf "\033[1;36m%s\033[0m\n" "$*"; }
c_green() { printf "\033[1;32m%s\033[0m\n" "$*"; }
c_red()   { printf "\033[1;31m%s\033[0m\n" "$*"; }
warn()    { printf "\033[1;33m! %s\033[0m\n" "$*"; }

step() { echo; c_blue ">> $*"; }

gen_secret() { openssl rand -hex 32; }

# ---------- 1. base packages ----------
step "Updating apt + installing base packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y curl git nginx ufw fail2ban ca-certificates gnupg openssl jq

# ---------- 2. Node.js 20 ----------
if ! command -v node >/dev/null 2>&1 || ! node -v | grep -qE '^v(2[0-9]|[3-9][0-9])'; then
  step "Installing Node.js 20.x"
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y nodejs
fi
if ! command -v pm2 >/dev/null 2>&1; then
  step "Installing PM2"
  npm i -g pm2
fi

# ---------- 3. Docker + compose ----------
if ! command -v docker >/dev/null 2>&1; then
  step "Installing Docker + compose plugin"
  apt-get install -y docker.io docker-compose-v2
  systemctl enable --now docker
fi

# ---------- 4. Certbot ----------
if ! command -v certbot >/dev/null 2>&1; then
  step "Installing Certbot"
  apt-get install -y certbot python3-certbot-nginx
fi

# ---------- 5. UFW firewall ----------
step "Configuring UFW (SSH + 80 + 443 only — Mongo/MinIO bound to 127.0.0.1)"
ufw --force enable >/dev/null 2>&1 || true
ufw allow OpenSSH || true
ufw allow 80 || true
ufw allow 443 || true

# ---------- 6. clone / pull repo ----------
step "Fetching $REPO ($BRANCH) → $APP_DIR"
mkdir -p "$(dirname "$APP_DIR")"
if [[ -d "$APP_DIR/.git" ]]; then
  git -C "$APP_DIR" fetch --all
  git -C "$APP_DIR" reset --hard "origin/$BRANCH"
else
  git clone --branch "$BRANCH" "$REPO" "$APP_DIR"
fi
cd "$APP_DIR"

# ---------- 7. .env (auto-generate if missing) ----------
ENV_FILE="$APP_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  step "Generating $ENV_FILE with random secrets"
  JWT_SECRET="$(gen_secret)"
  SESSION_COOKIE_SECRET="$(gen_secret)"
  GITHUB_WEBHOOK_SECRET="$(gen_secret)"
  INTERNAL_CRON_SECRET="$(gen_secret)"
  MONGO_PASSWORD="$(gen_secret | cut -c1-24)"
  S3_ACCESS_KEY="fms$(openssl rand -hex 4)"
  S3_SECRET_KEY="$(gen_secret | cut -c1-40)"
  APP_URL="https://${DOMAIN:-localhost}"

  cat > "$ENV_FILE" <<EOF
# Generated by bootstrap.sh on $(date -u +%FT%TZ)
NODE_ENV=production
APP_URL=$APP_URL
PORT=3000

JWT_SECRET=$JWT_SECRET
SESSION_COOKIE_SECRET=$SESSION_COOKIE_SECRET
SESSION_COOKIE_NAME=fms_session
SESSION_TTL_HOURS=12

MONGODB_URI=mongodb://fmsuser:$MONGO_PASSWORD@127.0.0.1:27017/filemanager?authSource=admin
MONGO_USER=fmsuser
MONGO_PASSWORD=$MONGO_PASSWORD

STORAGE_DRIVER=minio
S3_ENDPOINT=http://127.0.0.1:9000
S3_REGION=us-east-1
S3_ACCESS_KEY=$S3_ACCESS_KEY
S3_SECRET_KEY=$S3_SECRET_KEY
S3_FORCE_PATH_STYLE=true
S3_USE_SSL=false
S3_DEFAULT_BUCKET=filemanager

PUBLIC_URL_BASE=$APP_URL
PUBLIC_TOKEN_BYTES=24

GITHUB_WEBHOOK_SECRET=$GITHUB_WEBHOOK_SECRET
DEPLOY_BRANCH=$BRANCH
DEPLOY_SCRIPT=$APP_DIR/scripts/deploy.sh

MAX_UPLOAD_BYTES=524288000
REDIS_URL=
CLAMAV_HOST=
CLAMAV_PORT=3310

MAIL_DRIVER=noop
MAIL_HOST=
MAIL_PORT=587
MAIL_USER=
MAIL_PASS=
MAIL_FROM=File Manager <no-reply@${DOMAIN:-localhost}>

INTERNAL_CRON_SECRET=$INTERNAL_CRON_SECRET
RATE_LIMIT_PER_MIN=100
EOF
  chmod 600 "$ENV_FILE"
  c_green "  wrote $ENV_FILE (chmod 600)"
else
  warn ".env already exists — leaving it alone"
fi

# load env for subsequent steps
set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

# ---------- 8. infra (Mongo + MinIO) ----------
step "Starting Mongo + MinIO (localhost-only) via docker compose"
docker compose -f "$APP_DIR/docker-compose.yml" up -d
# wait for mongo healthcheck
for i in $(seq 1 30); do
  if docker compose -f "$APP_DIR/docker-compose.yml" ps mongo | grep -q "healthy"; then break; fi
  sleep 2
done

# ---------- 9. node deps + build ----------
step "Installing npm dependencies"
npm ci --silent
step "Running core-logic tests"
npm test
step "Building"
npm run build

# ---------- 10. seed first super_admin ----------
step "Seeding first super_admin (skips if one already exists)"
if [[ -n "$ADMIN_EMAIL" && -n "$ADMIN_PASS" ]]; then
  node scripts/seed-admin.js --email "$ADMIN_EMAIL" --password "$ADMIN_PASS" || true
elif [[ -n "${SUPER_ADMIN_EMAIL:-}" && -n "${SUPER_ADMIN_PASSWORD:-}" ]]; then
  node scripts/seed-admin.js || true
else
  warn "Run later with:  cd $APP_DIR && node scripts/seed-admin.js --email you@x.com --password '...'"
fi

# ---------- 11. PM2 ----------
step "Starting under PM2"
if pm2 jlist 2>/dev/null | grep -q '"name":"filemanager"'; then
  pm2 reload filemanager --update-env
else
  pm2 start ecosystem.config.js
fi
pm2 save
pm2 startup systemd -u root --hp /root >/dev/null 2>&1 || true

# ---------- 12. Nginx vhost ----------
if [[ -n "$DOMAIN" ]]; then
  step "Configuring Nginx for $DOMAIN"
  sed "s/files\.yourdomain\.com/$DOMAIN/g" "$APP_DIR/nginx/filemanager.conf" \
    > /etc/nginx/sites-available/filemanager
  ln -sf /etc/nginx/sites-available/filemanager /etc/nginx/sites-enabled/filemanager
  # Remove default if present
  rm -f /etc/nginx/sites-enabled/default
  nginx -t
  systemctl reload nginx
fi

# ---------- 13. SSL ----------
if [[ "$SKIP_SSL" -eq 0 && -n "$DOMAIN" && -n "$EMAIL" ]]; then
  step "Obtaining Let's Encrypt SSL cert for $DOMAIN"
  if ! certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos --email "$EMAIL" --redirect; then
    warn "Certbot failed — DNS may not yet point here. Re-run:"
    warn "  sudo certbot --nginx -d $DOMAIN"
  fi
elif [[ -n "$DOMAIN" ]]; then
  warn "Skipping SSL. To enable later:  sudo certbot --nginx -d $DOMAIN"
fi

# ---------- 14. cron ----------
step "Installing cron jobs"
bash "$APP_DIR/scripts/setup-cron.sh" || warn "Cron install failed — run manually with: bash $APP_DIR/scripts/setup-cron.sh"

# ---------- 15. final report ----------
echo
c_green "============================================================"
c_green " File Manager SaaS is up."
c_green "============================================================"
echo
echo "  URL:         ${APP_URL}/login"
echo "  Admin email: ${ADMIN_EMAIL:-<not seeded — see warning above>}"
echo "  App dir:     $APP_DIR"
echo "  Env file:    $ENV_FILE  (chmod 600)"
echo
echo "  Health:      curl ${APP_URL}/api/health"
echo "  Logs:        pm2 logs filemanager"
echo "  Update:      cd $APP_DIR && bash scripts/update.sh"
echo
echo "  GitHub webhook secret (paste into repo Settings → Webhooks):"
grep '^GITHUB_WEBHOOK_SECRET=' "$ENV_FILE" | cut -d= -f2-
echo
echo "  MinIO console (over SSH tunnel only — port 9001 is localhost-bound)"
echo "  S3 access key:  $(grep '^S3_ACCESS_KEY=' "$ENV_FILE" | cut -d= -f2-)"
echo
c_green "Done."
